### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Obwoya** [tormuto/BulkSMSWebsiteSourceCode#1]
Upon uploading the files on my server and installing... including filling all the required fields ... I recieved the 403 forbidden, with message "Request forbidden by administrative rules." Is there something I need to do or that I am doing badly.

**Comment by tormuto** [comment]
403 Forbidden messages has to do with htaccess, in this case the rules of the parent folder, into which you uploaded this source; that is preventing accesses to the sub-path. It doesn't have to do with the bulk-sms website source itself.

**Comment by Obwoya** [comment]
> 403 Forbidden messages has to do with htaccess, in this case the rules of the parent folder, into which you uploaded this source; that is preventing accesses to the sub-path. It doesn't have to do with the bulk-sms website source itself.

yes, true. I cleared my browser cache and i managed to have the site log in display. but I can't log in again with admin mail and password. Forgot password does not seem to work.

Could it be something wrong that I am doing?

**Comment by tormuto** [comment]
Please give clearer information - the information provided here is vague.
What does "does not seem to work" mean exactly.

**Comment by Obwoya** [comment]
It takes me nowhere. That's what I meant to say. because the login creds (admin email and Password) when enter them I get "Check the email for access link". My understanding is pretty basic, that I should look in either the inbox or spam/junk folders. And when I do, I do not get them there.

If I click on the "I Forget Password" nothing happens, like it is a dead end link. and when I look at the link that it references to, it is the same link requiring me to check the email for access link.

**Comment by tormuto** [comment]
If you don't get email it's because your smtp settings are incorrect;
You can check and adjust this from the file /configs.php that is at the base of the installation.

Meanwhile; that the message shows that you should check email for login code means the password is correct; no need for resetting password.

A bypass for login in without email code is through [YOUR_INSTALLATION_URL]/admin_login?override_e2fa=1
But you have to solve your smtp settings issue anyway, since a lot of things depends on the email functionality.

**Comment by Obwoya** [comment]
> If you don't get email it's because your smtp settings are incorrect;
> You can check and adjust this from the file /configs.php that is at the base of the installation.
> 
> Meanwhile; that the message shows that you should check email for login code means the password is correct; no need for resetting password.
> 
> A bypass for login in without email code is through [YOUR_INSTALLATION_URL]/admin_login?override_e2fa=1
> But you have to solve your smtp settings issue anyway, since a lot of things depends on the email functionality.

thanks man. let me try that. But at some point I was contemplating using the other credentials of bestsmsgateway.com.
